apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: p3bg3i6si-go 
  janus-idp.io/tekton: p3bg3i6si-go
  backstage.io/kubernetes-id: p3bg3i6si-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p3bg3i6si-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml