apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p3bg3i6si-go
  janus-idp.io/tekton: p3bg3i6si-go
  backstage.io/kubernetes-id: p3bg3i6si-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p3bg3i6si-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
